# Generated by Django 3.0.8 on 2020-11-17 05:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 11, 17, 5, 12, 44, 939857, tzinfo=utc)),
        ),
    ]
