# Generated by Django 3.0.8 on 2020-11-29 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201117_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 11, 29, 21, 50, 6, 807609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discussionmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 11, 29, 21, 50, 6, 809230, tzinfo=utc)),
        ),
    ]
