# Generated by Django 3.0.8 on 2020-12-02 05:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20201129_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 2, 5, 28, 57, 320292, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discussionmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 2, 5, 28, 57, 322721, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 2, 5, 28, 57, 319806, tzinfo=utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='replys',
            field=models.ManyToManyField(blank=True, null=True, to='main.Reply'),
        ),
    ]
