# Generated by Django 3.0.8 on 2020-12-03 06:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201203_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replys',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Discussion'),
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 3, 6, 57, 47, 795875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discussionmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 3, 6, 57, 47, 796569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 3, 6, 57, 47, 796237, tzinfo=utc)),
        ),
    ]
