# Generated by Django 3.0.8 on 2020-12-10 06:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201204_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='politicalview',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 6, 15, 0, 869902, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.Discussion'),
        ),
        migrations.AlterField(
            model_name='discussionmember',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 6, 15, 0, 870668, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discussionrequest',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='main.Discussion'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 12, 10, 6, 15, 0, 870274, tzinfo=utc)),
        ),
    ]
